spring:
  profiles:
    active: dev     # 开发配置
  http:
    encoding:
      force: true
      enabled: true
      charset: UTF-8
  mvc:
    throw-exception-if-no-handler-found: true       # 出现错误时, 直接抛出异常
  resources:
    add-mappings: false                             # 不要为资源文件建立映射
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8          # 东八区

server:
  tomcat:
    uri-encoding: UTF-8
  port: 9999    # 本地端口
